# Pandas

In [8]:
import pandas as pd
import numpy as np

In [6]:
sdata=pd.Series([0.25, 0.50, 0.75, 1.0])
print("sdata:\n", sdata)
print("type:",type(sdata))
print("sdata[1]:",sdata[1])
print("sdata.values:",sdata.values)
print("sdata.index:",sdata.index)

sdata:
 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
type: <class 'pandas.core.series.Series'>
sdata[1]: 0.5
sdata.values: [0.25 0.5  0.75 1.  ]
sdata.index: RangeIndex(start=0, stop=4, step=1)


In [9]:
sdata=pd.Series([0.25, 0.50, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print("sdata:\n",sdata)
print("sdata[b]: ",sdata['b'] )


sdata:
 a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
sdata[b]:  0.5


In [2]:
sdata=pd.Series([0.25, 0.50, 0.75, 1.0], index=[2, 5, 3, 7])
print("sdata:\n",sdata)
print("sdata[5]: ",sdata[5])


sdata:
 2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64
sdata[5]:  0.5


# Series as a specialized dictionary

In [5]:
population_dict={'California': 38332521,
                 'Texas': 26448163,
                 'New York': 19651127,
                 'Florida': 19552860,
                 'Illinois': 12882135}
print("Population_dict:\n", population_dict) #為排序的series
population=pd.Series(population_dict)
print("#population:\n", population)
print("#Type(population):", type(population))
print("#Population['California']:", population['California'])
print("#Population['Texas':'Florida']:\n", population['Texas':'Florida'])
print("#Population.sort_values():\n", population.sort_values()) #排序後的series

Population_dict:
 {'California': 38332521, 'Texas': 26448163, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}
#population:
 California    38332521
Texas         26448163
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
#Type(population): <class 'pandas.core.series.Series'>
#Population['California']: 38332521
#Population['Texas':'Florida']:
 Texas       26448163
New York    19651127
Florida     19552860
dtype: int64
#Population.sort_values():
 Illinois      12882135
Florida       19552860
New York      19651127
Texas         26448163
California    38332521
dtype: int64


In [6]:
# Create Series object using Scalar value
print("#series 5:\n", pd.Series(5, index=[100, 200, 300]))
print("#series 2a,1b,3c:\n", pd.Series({2:'a',1:'b', 3:'c'}, index=[3, 2]))


#series 5:
 100    5
200    5
300    5
dtype: int64
#series 2a,1b,3c:
 3    c
2    a
dtype: object


In [28]:
print("Population:\n", population)
area_dict={'California': 423967,
           'Texas': 695692,
           'New York': 141297,
           'Florida': 170312,
           'Illinois': 149995}
area=pd.Series(area_dict)
states=pd.DataFrame({'population':population,
                    'area':area})
print("\nStates:\n", states)
print("\nstates.index:\n", states.index)
print("states.columns:\n", states.columns)
print("\nstates['area']:\n", states['area'])

Population:
 California    38332521
Texas         26448163
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

States:
             population    area
California    38332521  423967
Texas         26448163  695692
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

states.index:
 Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
states.columns:
 Index(['population', 'area'], dtype='object')

states['area']:
 California    423967
Texas         695692
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


# Constructing DataFrame Objects
- From a single series object
- From a list of dictionaries
- From a dictionary of Series objects
- From a two-dimentional NumPy array
- From a NumPy structured array

In [34]:
print("type of population: ", type(population))
print("type of states: ", type(states))
populationDF=pd.DataFrame(population, columns=['population'])
print("populationDF: \n", populationDF)
print("\ntype of population: ", type(populationDF))


type of population:  <class 'pandas.core.series.Series'>
type of states:  <class 'pandas.core.frame.DataFrame'>
populationDF: 
             population
California    38332521
Texas         26448163
New York      19651127
Florida       19552860
Illinois      12882135

type of population:  <class 'pandas.core.frame.DataFrame'>


In [40]:
#Create the DataFrame From a list of dictionary
data=[{'a':i, 'b':2*i}
    for i in range(3)]
print("data:", data)
print("type of data:", type(data))
print("pd.DataFrame(data):\n", pd.DataFrame(data))
print("type of pd.DataFrame(data):", type(pd.DataFrame(data)))

#DataFrame can handle missing values
print("pd.DataFrame({'a':1, 'b':2},{'b':3, 'c':4}):\n", pd.DataFrame({'a':1, 'b':2},{'b':3, 'c':4}))


data: [{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]
type of data: <class 'list'>
pd.DataFrame(data):
    a  b
0  0  0
1  1  2
2  2  4
type of pd.DataFrame(data): <class 'pandas.core.frame.DataFrame'>
pd.DataFrame({'a':1, 'b':2},{'b':3, 'c':4}):
    a  b
b  1  2
c  1  2


In [45]:
#DataFrame can handle missing values
print("pd.DataFrame({'a':1, 'b':2},{'b':3, 'c':4}):\n", pd.DataFrame({'a':1, 'b':2},{'b':3, 'c':4}))

#Create DataFrame use two-dimentional NumPy array
print("pd.DataFrame(np.random.rand(3, 2)):\n", pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c']))

#Create an Index from the list of integer
ind=pd.Index([2, 3, 5, 7, 11])
print(ind)
print("ind[1]:", ind[1])
#ind[1]=0 --> TypeError: Index does not support mutable operations

pd.DataFrame({'a':1, 'b':2},{'b':3, 'c':4}):
    a  b
b  1  2
c  1  2
pd.DataFrame(np.random.rand(3, 2)):
         foo       bar
a  0.926434  0.635717
b  0.704050  0.737990
c  0.464303  0.388702
Int64Index([2, 3, 5, 7, 11], dtype='int64')
ind[1]: 3


# Index as ordered set

In [53]:
indA=pd.Index([1, 3, 5, 7, 9])
indB=pd.Index([2, 3, 5, 7, 11])
#indA & indB --> index.intersection(other) instead
print("indA: ", indA)
print("indB: ", indB)
print("intersection: ", indA.intersection(indB))

#indA | indB --> Use index.union(other) instead
print("union: ", indA.union(indB))

#Differences
#indA ^ indB --> index.symmetric_difference(other) instead
print("diiferences: ", indA.symmetric_difference(indB))

indA:  Int64Index([1, 3, 5, 7, 9], dtype='int64')
indB:  Int64Index([2, 3, 5, 7, 11], dtype='int64')
intersection:  Int64Index([3, 5, 7], dtype='int64')
union:  Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
diiferences:  Int64Index([1, 2, 9, 11], dtype='int64')


# Data Indexing and Selection
- Series as dictionary

In [62]:
data=pd.Series([0.25, 0.50, 0.75, 1.00], index=['a', 'b', 'c', 'd'])
print("data:\n", data)
print("\n\'a\' in data: ", 'a' in data)
print("data.key(): ", data.keys())
print("list(data.items()): ", list(data.items()))
data['e']=1.25 #add element
print("\ndata: \n", data)


data:
 a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

'a' in data:  True
data.key():  Index(['a', 'b', 'c', 'd'], dtype='object')
list(data.items()):  [('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

data: 
 a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64


In [66]:
#Slicing using explicit indexing
print("data['a':'c']:\n", data['a':'c'])

#Slicing using implicit indexing
print("\ndata[0:2]:\n", data[0:2])

print("\ndata:\n", data)


data['a':'c']:
 a    0.25
b    0.50
c    0.75
dtype: float64

data[0:2]:
 a    0.25
b    0.50
dtype: float64

data:
 a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64


In [70]:
#Masking
print("data[(data>0.3)&(data<0.8)]: \n", data[(data>0.3)&(data<0.8)])

#Fancy Indexing, list of indices Fancy Indexing 指傳遞索引陣列以便一次得到多個陣列元素。
#https://medium.com/allen%E7%9A%84%E6%8A%80%E8%A1%93%E7%AD%86%E8%A8%98/python-numpy-fancy-indexing-ff1ac286d671
print("\ndata[['a', 'd']]: \n", data[['a', 'd']])

#Index

data[(data>0.3)&(data<0.8)]: 
 b    0.50
c    0.75
dtype: float64

data[['a', 'd']]: 
 a    0.25
d    1.00
dtype: float64


# Indexer loc and iloc

In [79]:
data=pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
print("data:\n", data)

#to access data using index it using explicit indexing
print("data[1]:", data[1])
#to access data using slicing it uses implicit indexing
print("data[1:3]:\n", data[1:3])
#loc uses explicit(明顯的) indexing
print("\ndata.loc[1]: ", data.loc[1])
#iloc uses implicit(隱晦的) indexing
print("data.iloc[1]: ", data.iloc[1])

data:
 1    a
3    b
5    c
dtype: object
data[1]: a
data[1:3]:
 3    b
5    c
dtype: object

data.loc[1]:  a
data.iloc[1]:  b


# Data selection in DataFrame
## DataFrame as a dictionary

In [21]:
pop=pd.Series({'California': 38332521,
                'Texas': 26448163,
                'New York': 19651127,
                'Florida': 19552860,
                'Illinois': 12882135})

area=pd.Series({'California': 423967,
                'Texas': 695692,
                'New York': 141297,
                'Florida': 170312,
                'Illinois': 149995})

data=pd.DataFrame({'area':area,
                    'pop':pop})

print("data:\n", data)



data:
               area       pop
California  423967  38332521
Texas       695692  26448163
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135


In [23]:
#Dictionary style indexing  
print("area:\n", data['area'])

#attribute style
print("\ndata.area:\n", data.area)

#are we getting the same data from using different methods
print("\ndata.area is data['area']:", data.area is data['area'])



area:
 California    423967
Texas         695692
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

data.area:
 California    423967
Texas         695692
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

data.area is data['area']: True


In [24]:
print("\ndata.pop:\n", data.pop)
print("\ndata['pop']:\n", data['pop'])
print("\ndata.pop is data['pop']:", data.pop is data['pop'])


data.pop:
 <bound method DataFrame.pop of               area       pop
California  423967  38332521
Texas       695692  26448163
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

data['pop']:
 California    38332521
Texas         26448163
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

data.pop is data['pop']: False


In [25]:
# data.pop = avoid using attribute style indexing to modify the value
data['pop']
data['density']=data['pop']/data['area']
print("data:\n", data)

#to get the values of DataFrame
print("data.values:\n", data.values)

#to  get the first row of the dataframe
print("data.values[0]:\n", data.values[0])





data:
               area       pop     density
California  423967  38332521   90.413926
Texas       695692  26448163   38.017058
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
data.values:
 [[4.23967000e+05 3.83325210e+07 9.04139261e+01]
 [6.95692000e+05 2.64481630e+07 3.80170578e+01]
 [1.41297000e+05 1.96511270e+07 1.39076746e+02]
 [1.70312000e+05 1.95528600e+07 1.14806121e+02]
 [1.49995000e+05 1.28821350e+07 8.58837628e+01]]
data.values[0]:
 [4.23967000e+05 3.83325210e+07 9.04139261e+01]


In [26]:
#Slicing using implicit indexing
print("data.iloc[:3, :2]:\n", data.iloc[:3, :2])

#Explicit  index includes the final index
print("data.loc[:'Illinois', :'pop']:\n", data.loc[:'Illinois', :'pop'])

print("data.loc[:'Florida', :'density']:\n", data.loc[:'Florida', :'density'])

data.iloc[:3, :2]:
               area       pop
California  423967  38332521
Texas       695692  26448163
New York    141297  19651127
data.loc[:'Illinois', :'pop']:
               area       pop
California  423967  38332521
Texas       695692  26448163
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135
data.loc[:'Florida', :'density']:
               area       pop     density
California  423967  38332521   90.413926
Texas       695692  26448163   38.017058
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121


In [29]:
#loc and iloc can combine masking and fancy indexing
print("#combination: \n", data.loc[data.density>100, ['pop', 'density']])
print("#data:\n", data)

#Modify DataFrame using iloc
data.iloc[0,2]=90
print("#modified data:\n", data)

#swap columns and rows using transpose()
#https://note.nkmk.me/en/python-pandas-t-transpose/
print("#Swap:\n", data.transpose())



#combination: 
                pop     density
New York  19651127  139.076746
Florida   19552860  114.806121
#data:
               area       pop     density
California  423967  38332521   90.000000
Texas       695692  26448163   38.017058
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
#modified data:
               area       pop     density
California  423967  38332521   90.000000
Texas       695692  26448163   38.017058
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
#Swap:
          California         Texas      New York       Florida      Illinois
area       423967.0  6.956920e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      38332521.0  2.644816e+07  1.965113e+07  1.955286e+07  1.288214e+07
density        90.0  3.801706e+01  1.390767e+02  1.148061e+02  8.588376e+01


# Operating on Data in Pandas

In [30]:
#Series
rng=np.random.RandomState(42)
ser=pd.Series(rng.randint(0, 10, 4))
print("#ser:\n", ser)

#DataFrame
df=pd.DataFrame(rng.randint(0, 10,(3, 4)), columns=['a', 'b', 'c', 'd'])
print("#df:\n", df)

#Index preserve in Series offer applying NumPy operation
#以自然常数e为底的指数函数: https://blog.csdn.net/Ericsson_Liu/article/details/81271021
print("#exp(ser):\n", np.exp(ser))

#Index preserves in DataFrame
print("#sin(df*np.pi/4):\n", np.sin(df*np.pi/4))


#ser:
 0    6
1    3
2    7
3    4
dtype: int32
#df:
    a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4
#exp(ser):
 0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64
#sin(df*np.pi/4):
           a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16


# Indexing Alignment in Series

In [32]:
area=pd.Series({'Alaska':1723337,
                'Texas': 695692,
                'California': 423967
                })
print("#area:\n", area)
population=pd.Series({'California': 38332521,
                'Texas': 26448193,
                'New York':19651127
                })
print("\n#population:\n", population)
print("\n#area/population:\n", area/population)
print("\n#area.index.union(population.index):\n", area.index.union(population.index))

#area:
 Alaska        1723337
Texas          695692
California     423967
dtype: int64

#population:
 California    38332521
Texas         26448193
New York      19651127
dtype: int64

#area/population:
 Alaska             NaN
California    0.011060
New York           NaN
Texas         0.026304
dtype: float64

#area.index.union(population.index):
 Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')


# Index Alignment in DataFrame

In [35]:
A=pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('xy'))
print("#A:\n", A)
B=pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('xyz'))
print("\n#B:\n", B)
print("\n#A+B:\n", A+B)



#A:
     x   y
0   8   1
1  19  14

#B:
    x  y  z
0  6  7  2
1  0  3  1
2  7  3  1

#A+B:
       x     y   z
0  14.0   8.0 NaN
1  19.0  17.0 NaN
2   NaN   NaN NaN


In [37]:
#pd.stack(): https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html
#np.stack(): https://numpy.org/doc/stable/reference/generated/numpy.stack.html
fill=A.stack().mean() #所有A內的數值相加取平均
print("\n#fill:\n", fill)
print("\n#A.add(B, fill_value=fill):\n", A.add(B, fill_value=fill))
print("\n#B:\n", B)


#fill:
 10.5

#A.add(B, fill_value=fill):
       x     y     z
0  14.0   8.0  12.5
1  19.0  17.0  11.5
2  17.5  13.5  11.5

#B:
    x  y  z
0  6  7  2
1  0  3  1
2  7  3  1


# Operations Between Series and DataFrame
- Operations between Series and DataFrame are similar as operations between one-dimentional and two-dimentional array

In [39]:
rng= np.random.RandomState(42)
A= rng.randint(10, size=(3, 4))
print("\n#A:\n", A)
print("\n#A[0]: \n", A[0])
print("\n#A-A[0]:\n", A-A[0]) #每一row皆減A[0]


#A:
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]

#A[0]: 
 [6 3 7 4]

#A-A[0]:
 [[ 0  0  0  0]
 [ 0  6 -5  2]
 [ 1  1 -4  3]]


In [45]:
#Create DataFrame
df=pd.DataFrame(A, columns=list('QRST'))
print("#df:\n", df)
print("\n#df.iloc[0]:\n", df.iloc[0])

#By default the operation is done row-wise
print("\n#df-df.iloc[0]:\n", df-df.iloc[0])



#df:
    Q  R  S  T
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

#df.iloc[0]:
 Q    6
R    3
S    7
T    4
Name: 0, dtype: int32

#df-df.iloc[0]:
    Q  R  S  T
0  0  0  0  0
1  0  6 -5  2
2  1  1 -4  3


In [47]:
#Substracting one of the column elements to rest of the columm elements
print("#df:\n", df)
print("\n#df.subtract(df['R'], axis=0):\n", df.subtract(df['R'], axis=0)) #每一column減掉df['R']那一column的值

#Substracting one element of a column to rest of the elements in column
halfrow = df.iloc[0, ::2]
print("\n#halfrow:\n", halfrow)
print("\n#df-halfrow:\n", df-halfrow)

#df:
    Q  R  S  T
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

#df.subtract(df['R'], axis=0):
    Q  R  S  T
0  3  0  4  1
1 -3  0 -7 -3
2  3  0 -1  3

#halfrow:
 Q    6
S    7
Name: 0, dtype: int32

#df-halfrow:
      Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN -5.0 NaN
2  1.0 NaN -4.0 NaN


# Operating on Null Values
- Pandas provide seceral useful functions for detecting, removing and replacing null values
- isnull() #generates the boolean mask indicating missing values
- notnull() #opposite of isnull()
- fillna() #missing values filled

## Detecting Null Values

In [57]:
data=pd.Series([1, np.nan, 'hello', None]) #np.nan=none value
print("#data: \n", data)
print("\n#data.isnull: \n", data.isnull())

#data: 
 0        1
1      NaN
2    hello
3     None
dtype: object

#data.isnull: 
 0    False
1     True
2    False
3     True
dtype: bool


- fillter out the null values

In [58]:
print("#data[data.notnull()]: \n", data[data.notnull()])

#Removal of NA values for seroes
ser1=data.dropna()
print("\n#ser1: \n", ser1)



#data[data.notnull()]: 
 0        1
2    hello
dtype: object

#ser1: 
 0        1
2    hello
dtype: object


# Operating on DataFrames

In [62]:
df=pd.DataFrame([[1, np.nan, 2], 
                [2, 3, 5],
                [np.nan, 4, 6]])
print("\n#df:\n", df)
print("\n#df.dropna(axis='columns'):\n", df.dropna(axis='columns'))

#Creating the nan value column
df[3]=np.NaN
print("\n#df:\n", df)
print("\n#df.dropna(axis='columns'):\n", df.dropna(axis='columns', how='all'))

#Specifying the minimum number we want to keep to remove Nan
print(df.dropna(axis='rows', thresh=3))


#df:
      0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

#df.dropna(axis='columns'):
    2
0  2
1  5
2  6

#df:
      0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

#df.dropna(axis='columns'):
      0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6
     0    1  2   3
1  2.0  3.0  5 NaN


# Filling Null Values

In [68]:
data=pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
print("#data:\n", data)
print("\n#data.fillna(0):\n", data.fillna(0))


#data:
 a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

#data.fillna(0):
 a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64


In [67]:
#forward fill
print("\n#data.fillna(method='ffill'):\n", data.fillna(method='ffill'))
#Backward fill
print("\n#data.fillna(method='bfill'):\n", data.fillna(method='bfill'))
print("\n#data.fillna(method='ffill', axis=1):\n", df.fillna(method='ffill', axis=1))


#data.fillna(method='ffill'):
 a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

#data.fillna(method='bfill'):
 a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

#data.fillna(method='ffill', axis=1):
      0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0


# Hierarchical Indexing
## Multiple Indexed Series

In [73]:
#Using Python Tuples as Keys
index= [('california', 2000), ('california', 2010),
        ('New York', 2000), ('New York', 2010),
        ('Texas', 2000), ('Texas', 2010)]
population=[33871648, 37253956,
            18976457, 19378102,
            20851820, 25145561]
pop=pd.Series(population, index=index)
print("#pop:\n", pop)
print("\n#pop of limited range:\n", pop[('New York', 2000):('Texas', 2010)])



#pop:
 (california, 2000)    33871648
(california, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

#pop of limited range:
 (New York, 2000)    18976457
(New York, 2010)    19378102
(Texas, 2000)       20851820
(Texas, 2010)       25145561
dtype: int64


In [77]:
#Converting python tuple multi-index into pandas multi-index
index=pd.MultiIndex.from_tuples(index)
print("#index:\n", index)
pop=pop.reindex(index)


#index:
 MultiIndex([('california', 2000),
            ('california', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )


In [87]:
print("\n#pop :\n", pop)
print(pop['New York':'Texas'])
#誤誤誤
print(pop[:, 2000])


#pop :
 california  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [79]:
#Converting Multi-index series into indexed dataframe using unstack()
pop_df=pop.unstack()
print(pop_df)

                2000      2010
New York    18976457  19378102
Texas       20851820  25145561
california  33871648  37253956


In [80]:
# What if we want to add another column of demographic dta (under 18)
pop_df=pd.DataFrame({'total':pop, 
                    'under18':[9267089, 9284094,
                                4687371, 4318033,
                                4506301, 6879014]})
print(pop_df)

                    total  under18
california 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687371
           2010  19378102  4318033
Texas      2000  20851820  4506301
           2010  25145561  6879014


In [84]:
f_u18=pop_df['under18']/pop_df['total']
print(f_u18.unstack())

                2000      2010
New York    0.247010  0.222831
Texas       0.216111  0.273568
california  0.273594  0.249211


# Method of MultiIndex Creation
- List
- Dictionary
- Multi-index constructors

## Creating multi-index by List

In [88]:
df=pd.DataFrame(np.random.rand(4, 2),
                index=[['a','a', 'b', 'b'], [1, 2, 1, 2]],
                columns=['data1', 'data2'])
print(df)

        data1     data2
a 1  0.807510  0.856993
  2  0.521667  0.962260
b 1  0.412672  0.981711
  2  0.761502  0.394684


In [91]:
data={('california', 2000):33871648,
        ('california', 2010):37253956,
        (  'New York', 2000):18976457,
        (  'New York', 2010):19378102,
        (     'Texas', 2000):20851820,
        (     'Texas', 2010):25145561}
print(data)
print(pd.Series(data))

{('california', 2000): 33871648, ('california', 2010): 37253956, ('New York', 2000): 18976457, ('New York', 2010): 19378102, ('Texas', 2000): 20851820, ('Texas', 2010): 25145561}
california  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


## Explicit Multi-index Constructor

In [93]:
#from the list of arrays
print(pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]]))
#from the list of tuples
print(pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)]))
#From a cartesian product of single series
print(pd.MultiIndex.from_product([['a', 'b'],[1, 2]]))

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


## MultiIndex level names

In [95]:
print(pop)
pop.index.names=['state', 'year']
print(pop)

california  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64
state       year
california  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


## MultiIndex for Columns

In [99]:
#Creating medical data
#Hierarchical indices and columns
index=pd.MultiIndex.from_product([[2013, 2014],[1,2]], 
                                names=['year', 'visit'])
columns=pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'],
                                    ['Heart_Rate', 'Temperature']],
                                    names=['patient', 'measurement'])
#Create  some data
data=np.round(np.random.randn(4, 6), 1) #round of 1
print("#original data:\n", data)
data[:, ::2]*=10
print("\n#data[:, ::2]*=10:\n", data)
data+=37
print("\n#data+=37:\n", data)
print("\n#abs(data):\n", abs(data))


#original data:
 [[-0.4 -1.3  0.3  0.3 -1.8 -0.1]
 [-0.7  0.6 -1.1  0.8  0.5  0.1]
 [ 0.8  1.7  1.4  1.4  0.1 -0.1]
 [-0.5  0.6  0.8  0.2 -0.6  0.3]]

#data[:, ::2]*=10:
 [[ -4.   -1.3   3.    0.3 -18.   -0.1]
 [ -7.    0.6 -11.    0.8   5.    0.1]
 [  8.    1.7  14.    1.4   1.   -0.1]
 [ -5.    0.6   8.    0.2  -6.    0.3]]

#data+=37:
 [[33.  35.7 40.  37.3 19.  36.9]
 [30.  37.6 26.  37.8 42.  37.1]
 [45.  38.7 51.  38.4 38.  36.9]
 [32.  37.6 45.  37.2 31.  37.3]]

#abs(data):
 [[33.  35.7 40.  37.3 19.  36.9]
 [30.  37.6 26.  37.8 42.  37.1]
 [45.  38.7 51.  38.4 38.  36.9]
 [32.  37.6 45.  37.2 31.  37.3]]


In [101]:
#Create the DataFrame 
health_data=pd.DataFrame(data, index=index, columns=columns)
health_data

patient            Bob                  Guido                    Sue  \
measurement Heart_Rate Temperature Heart_Rate Temperature Heart_Rate   
year visit                                                             
2013 1            33.0        35.7       40.0        37.3       19.0   
     2            30.0        37.6       26.0        37.8       42.0   
2014 1            45.0        38.7       51.0        38.4       38.0   
     2            32.0        37.6       45.0        37.2       31.0   

patient                  
measurement Temperature  
year visit               
2013 1             36.9  
     2             37.1  
2014 1             36.9  
     2             37.3

In [102]:
#Access the data of a person
health_data['Guido']

measurement  Heart_Rate  Temperature
year visit                          
2013 1             40.0         37.3
     2             26.0         37.8
2014 1             51.0         38.4
     2             45.0         37.2

In [103]:
#Access the data of a person from a particular year
health_data.loc[2013, 'Guido']

measurement  Heart_Rate  Temperature
visit                               
1                  40.0         37.3
2                  26.0         37.8

In [108]:
#Recover patient heart rate 
print(health_data['Guido', 'Heart_Rate'])
#Access first two rows and first four columns
print(health_data.iloc[:2, :4])
#Recover patient heart rate of Guido using slicing
print(health_data.loc[:, ('Guido', 'Heart_Rate')])


year  visit
2013  1        40.0
      2        26.0
2014  1        51.0
      2        45.0
Name: (Guido, Heart_Rate), dtype: float64
patient            Bob                  Guido            
measurement Heart_Rate Temperature Heart_Rate Temperature
year visit                                               
2013 1            33.0        35.7       40.0        37.3
     2            30.0        37.6       26.0        37.8
year  visit
2013  1        40.0
      2        26.0
2014  1        51.0
      2        45.0
Name: (Guido, Heart_Rate), dtype: float64


In [109]:
#Access the heart rate of all patients first visit using tuple of multiple indices
print(health_data.loc[(:, 1),(:, 'Heart_Rate')])

SyntaxError: invalid syntax (3488508798.py, line 2)

In [114]:
# IndexSlice
idx=pd.IndexSlice
print(health_data.loc[idx[:, 1], idx[:, 'Heart_Rate']])
#Access the heart rate of Bob's first visit in 2014 using IndexSlice
print(health_data.loc[idx[2014, 1], idx['Bob', 'Heart_Rate']])
#Access the heart rate and temperature of Bob and Sue's first visit in 2014 using IndexSlice
print(health_data.loc[idx[2014, 1], idx[['Bob', 'Sue'], 'Heart_Rate':'Temperature']])


patient            Bob      Guido        Sue
measurement Heart_Rate Heart_Rate Heart_Rate
year visit                                  
2013 1            33.0       40.0       19.0
2014 1            45.0       51.0       38.0
45.0
patient  measurement
Bob      Heart_Rate     45.0
         Temperature    38.7
Sue      Heart_Rate     38.0
         Temperature    36.9
Name: (2014, 1), dtype: float64


## Data Aggregation 


In [116]:
#上面那一格: 缺缺缺
#Average out the measurement in the two visits each year
data_mean=health_data.mean(level='year') #row wise aggregation
data_mean

C:\Users\hsian\AppData\Local\Temp\ipykernel_17252\752183661.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean=health_data.mean(level='year')


patient            Bob                  Guido                    Sue  \
measurement Heart_Rate Temperature Heart_Rate Temperature Heart_Rate   
year                                                                   
2013              31.5       36.65       33.0       37.55       30.5   
2014              38.5       38.15       48.0       37.80       34.5   

patient                  
measurement Temperature  
year                     
2013               37.0  
2014               37.1

In [117]:
data_mean.mean(axis=1, level='measurement')

C:\Users\hsian\AppData\Local\Temp\ipykernel_17252\4139955395.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  data_mean.mean(axis=1, level='measurement')


measurement  Heart_Rate  Temperature
year                                
2013          31.666667    37.066667
2014          40.333333    37.683333

## Combining Datasets: Concatenate

In [120]:
# one dimesional array
x=[1, 2, 3]
y=[4, 5, 6]
z=[7, 8, 9]
print(np.concatenate([x, y, z]))
#two dimentional array
x=[[1, 2], [3, 4]]
print(np.concatenate([x, x], axis=1))


[1 2 3 4 5 6 7 8 9]
[[1 2 1 2]
 [3 4 3 4]]


## Concatenation in Series and DataFrame
- pd.concat()

In [125]:
ser1=pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2=pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
print("#pd.concat([ser1, ser2])\n", pd.concat([ser1, ser2]))



#pd.concat([ser1, ser2])
 1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [126]:
#Create the Data for DataFrame
df1=pd.DataFrame(np.arange(0, 9).reshape(3, 3), 
                index=[1, 2, 3],
                columns=['a', 'b', 'c'])
print("\n#df1\n", df1)
df2=pd.DataFrame(np.arange(9, 18).reshape(3, 3), 
                index=[4, 5, 6],
                columns=['a', 'b', 'c'])
print("\n#df2\n", df2)

#Combining two dataframe
print("\n#pd.concat([df1, df2])\n", pd.concat([df1, df2]))


#df1
    a  b  c
1  0  1  2
2  3  4  5
3  6  7  8

#df2
     a   b   c
4   9  10  11
5  12  13  14
6  15  16  17

#pd.concat([df1, df2])
     a   b   c
1   0   1   2
2   3   4   5
3   6   7   8
4   9  10  11
5  12  13  14
6  15  16  17


In [129]:
df3=pd.DataFrame(np.arange(18, 27).reshape(3, 3), 
                index=[1, 2, 3],
                columns=['d', 'e', 'f'])
print("#df3\n", df3)
#Combine two dataframe column wise
print("\n#pd.concat([df1, df3], axis=1)\n", pd.concat([df1, df3], axis=1))


#df3
     d   e   f
1  18  19  20
2  21  22  23
3  24  25  26

#pd.concat([df1, df3], axis=1)
    a  b  c   d   e   f
1  0  1  2  18  19  20
2  3  4  5  21  22  23
3  6  7  8  24  25  26
